# Generated by Django 4.1.9 on 2023-05-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notes_chat_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_msg', models.CharField(max_length=60)),
                ('content', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
