# Generated by Django 4.1.9 on 2023-05-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatmessage_delete_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
